var template = {
    "Default": {
        "hasRestriction": true,
        "restrictions": ["monster[i][\"appearsInThisGame\"] == \"yes\""],
        "displayName": "Default ",
        "displayOrder": 0,
        "sizeMod": "none",
        "typeMod": "none",
        "alignmentMod": "none",
        "acModType": "mod",
        "acMod": 0,
        "strType": "none",
        "dexType": "none",
        "conType": "none",
        "intType": "none",
        "wisType": "none",
        "chaType": "none",
        "traitModType": "none",
        "actionModType": "none",
        "legendaryModType": "none",
        "languageModType": "none",
        "speedModType": "none",
        "senseModType": "none",
        "dmgResistModType": "none",
        "vulnerableModType": "none",
        "dmgImmuneModType": "none",
        "condImmuneModType": "none",
        "hpMod": "none",
        "hitDiceMod": 0,
        "hitDieMod": 0,
        "str": 0,
        "dex": 0,
        "con": 0,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "trait": [],
        "action": [],
        "legendary": [],
        "languages": "",
        "speed": "",
        "resist": "",
        "immune": "",
        "conditionImmune": "",
        "vulnerable": "",
        "senses": ""

    },
    "Badass": {
        "displayName": "Badass ",
        "displayOrder": 0,
        "sizeMod": "none",
        "typeMod": "none",
        "alignmentMod": "none",
        "acModType": "mod",
        "acMod": 3,
        "strType": "mod",
        "dexType": "mod",
        "conType": "mod",
        "intType": "mod",
        "wisType": "mod",
        "chaType": "mod",
        "traitModType": "add",
        "actionModType": "none",
        "legendaryModType": "none",
        "languageModType": "none",
        "speedModType": "none",
        "senseModType": "none",
        "dmgResistModType": "none",
        "vulnerableModType": "none",
        "dmgImmuneModType": "none",
        "condImmuneModType": "none",
        "hpMod": 1,
        "hitDiceMod": 3,
        "hitDieMod": 1,
        "str": 4,
        "dex": 4,
        "con": 4,
        "int": 4,
        "wis": 4,
        "cha": 4,
        "hasRestriction": false,
        "trait": [ {
            "name": "Legendary Resistance (+1/Day)",
            "text": "If the badass fails a saving throw, it can choose to succeed instead."
          }],
        "action": [],
        "legendary": [],
        "languages": "",
        "speed": ""
    },
    "Defender": {
        "hasRestriction": false,
        "restrictions": [],
        "displayName": " Defender",
        "displayOrder": 1,
        "sizeMod": "none",
        "typeMod": "none",
        "alignmentMod": "none",
        "acModType": "mod",
        "acMod": 2,
        "strType": "none",
        "dexType": "mod",
        "conType": "mod",
        "intType": "none",
        "wisType": "none",
        "chaType": "none",
        "traitModType": "add",
        "actionModType": "none",
        "legendaryModType": "none",
        "languageModType": "none",
        "speedModType": "none",
        "senseModType": "none",
        "dmgResistModType": "add",
        "vulnerableModType": "none",
        "dmgImmuneModType": "none",
        "condImmuneModType": "none",
        "hpMod": 1,
        "hitDiceMod": 1,
        "hitDieMod": 0,
        "str": 0,
        "dex": 4,
        "con": 4,
        "int": 0,
        "wis": 0,
        "cha": 0,
        "trait": [
            {
                "name": "Sentinel",
                "text": "When the defender strikes a creature with an opportunity attack, that creature's speed becomes 0 for the rest of its turn."
            }
        ],
        "action": [],
        "legendary": [],
        "languages": "",
        "speed": "",
        "resist": "bludgeoning, piercing, and slashing from nonmagical weapons",
        "immune": "",
        "conditionImmune": "",
        "vulnerable": ""

    },
    "Lil'": {
        "displayName": "Lil' ",
        "displayOrder": 0,
        "sizeMod": -1,
        "typeMod": "none",
        "alignmentMod": "none",
        "acModType": "mod",
        "acMod": 1,
        "strType": "mod",
        "dexType": "mod",
        "conType": "mod",
        "intType": "none",
        "wisType": "none",
        "chaType": "none",
        "traitModType": "none",
        "actionModType": "none",
        "legendaryModType": "none",
        "languageModType": "none",
        "speedModType": "none",
        "senseModType": "none",
        "dmgResistModType": "none",
        "vulnerableModType": "none",
        "dmgImmuneModType": "none",
        "condImmuneModType": "none",
        "hitDieMod": -1,
        "hpMod": 1,
        "str": -2,
        "dex": +2,
        "con": -2,
        "hasRestriction": true,
        "restrictions": ["monster[i][\"size\"] != \"Tiny\""],
        "trait": [],
        "action": [],
        "legendary": [],
        "languages": "",
        "speed": ""
    },
    "Skeletal": {
        "displayName": "Skeletal ",
        "displayOrder": 0,
        "sizeMod": "none",
        "typeMod": "undead",
        "alignmentMod": "Lawful evil",
        "acModType": "mod",
        "acMod": -1,
        "strType": "none",
        "dexType": "none",
        "conType": "set",
        "intType": "min",
        "wisType": "min",
        "chaType": "min",
        "traitModType": "add",
        "actionModType": "none",
        "legendaryModType": "none",
        "languageModType": "none",
        "speedModType": "none",
        "senseModType": "add",
        "dmgResistModType": "none",
        "vulnerableModType": "add",
        "dmgImmuneModType": "add",
        "condImmuneModType": "add",
        "hpMod": 1,
        "con": 15,
        "int": 6,
        "wis": 8,
        "cha": 5,
        "senses": "darkvision 60 ft.",
        "hasRestriction": true,
        "restrictions": ["monster[i][\"type\"] == \"beast\" || monster[i][\"type\"] == \"dragon\" || monster[i][\"type\"] == \"fey\" || monster[i][\"type\"] == \"giant\" || monster[i][\"type\"] == \"monstrosity\" || monster[i][\"type\"] == \"aberration\" || monster[i][\"type\"] == \"humanoid\""],
        "trait": [{
                "name": "Undead Nature",
                "text": "A skeleton doesn't require air, food, drink, or sleep."
            },
            {
                "name": "Other Traits",
                "text": "The skeleton keeps all the other traits it had in life, except for those that rely on flesh, organs, or internal functions. Cannot cast spells and loses all spell slots."
            },
            {
                "name": "Darkvision",
                "text": "The skeletal form of this creature has darkvision out to a range of 60 ft., unless it had superior darkvision (120 ft.) in life."
            }
        ],
        "immune": "poison",
        "conditionImmune": "exhaustion, poisoned",
        "vulnerable": "bludgeoning"
    }, 
    "Hollowed Carrier": {
        "hasRestriction": true,
        "restrictions": ["monster[i][\"size\"] != \"Tiny\" && (monster[i][\"type\"] == \"humanoid\" || monster[i][\"type\"] == \"beast\" || monster[i][\"type\"] == \"giant\" || monster[i][\"type\"] == \"dragon\")"],
        "displayName": "Hollowed Carrier ",
        "displayOrder": 0,
        "sizeMod": "none",
        "typeMod": "none",
        "alignmentMod": "none",
        "acModType": "set",
        "acMod": 12,
        "strType": "mod",
        "dexType": "mod",
        "conType": "mod",
        "intType": "mod",
        "wisType": "mod",
        "chaType": "mod",
        "traitModType": "add",
        "actionModType": "add",
        "legendaryModType": "none",
        "languageModType": "none",
        "speedModType": "none",
        "senseModType": "add",
        "dmgResistModType": "none",
        "vulnerableModType": "none",
        "dmgImmuneModType": "add",
        "condImmuneModType": "add",
        "hpMod": "none",
        "hitDiceMod": 0,
        "hitDieMod": 0,
        "str": 2,
        "dex": 1,
        "con": 2,
        "int": -2,
        "wis": -2,
        "cha": -4,
        "trait": [ 
            {
                "name": "Improved Grappling",
                "text": "The Hallowed Carrier gets a +2 to Strength (Athletics) checks, and it gains Advantage on attack rolls made against a creature it's grappling."
            },
            {
                "name": "Corpse Seeker",
                "text": "The Hallowed Carrier is drawn to graveyards or other places filled with the dead, whereupon reaching it uses its necrotic eruption ability in order for the corpse worms it harbors to feast."
            },
            {
                "name": "Necrotic Strength",
                "text": "Any melee attack the creature possessed goes up 1 die size (ex: a 1d4 becomes a 1d6), except d12s which are instead doubled. All of its melee attacks do Necrotic damage."
            },
            {
                "name": "Infested with Worms",
                "text": "Any grapple or the ability ‘Worm Slam’ are immediately followed by the ‘Bites of the Worm’ attack as a free action."
            }

        ],
        "action": [ 
            {
            "name": "Pin",
            "text": "The Hallowed Carrier tries to pin a creature it has grappled. To do so, it makes another grapple check. If it succeeds, the Hollowed Carrier and the creature it grappled are both restrained until the grapple ends."
            },
            {
                "name": "Worm Slam",
                "text": "Melee Weapon Attack: +6 to hit, reach 5ft., one target. Hit: 11 (2d10) bludgeoning damage."
            },
            {
                "name": "Bites of the Worm",
                "text": "Melee Weapon Attack: +2 to hit, reach 0 ft., one creature grappled by or just struck by the Hollowed Carrier or otherwise occupying the same space as the hollowed carrier. Hit: 20 (4d8) piercing damage, or 10 (2d8) piercing damage if the Hollowed Carrier has half hit points or fewer."
            },
            {
                "name": "Necrotic Eruption",
                "text": "The Hollowed Carrier erupts in a 15-foot radius around itself. Each creature in that area must make a DC 12 Dexterity Saving Throw, taking 21 (6d6) Necrotic damage on a failed save, or half as much on a successful one. This eruption releases a Swarm of Corpse Worms in the middle of the blast, unaffected by the blast itself. If the Hallowed Carrier is slain, this action automatically activates unless the Hollowed Carrier is slain in such a way that it leaves no corpse."
            },
            {
                "name": "Black Tentacles",
                "text": "The Hollowed Carrier may cast Evard's Black Tentacles once."
            }
    ],
        "legendary": [],
        "languages": "",
        "speed": "",
        "resist": "",
        "immune": "cold, necrotic, poison",
        "conditionImmune": "charmed, exhaustion, frightened, paralyzed, petrified, prone",
        "vulnerable": "",
        "senses": "blindsight 30 ft."

    }

}