var wordList = [
'come',
'get',
'give',
'go',
'keep',
'let',
'make',
'put',
'seem',
'take',
'be',
'do',
'have',
'say',
'see',
'send',
'may',
'will',
'about',
'across',
'after',
'against',
'among',
'at',
'before',
'between',
'by',
'down',
'from',
'in',
'off',
'on',
'over',
'through',
'to',
'under',
'up',
'with',
'as',
'for',
'of',
'till',
'than',
'the',
'all',
'any',
'every',
'little',
'much',
'no',
'other',
'some',
'such',
'that',
'this',
'he',
'you',
'who',
'and',
'because',
'but',
'or',
'if',
'though',
'while',
'how',
'when',
'where',
'why',
'again',
'ever',
'far',
'forward',
'here',
'near',
'now',
'out',
'still',
'then',
'there',
'together',
'well',
'almost',
'enough',
'even',
'not',
'only',
'quite',
'so',
'very',
'tomorrow',
'yesterday',
'account',
'act',
'addition',
'adjustment',
'advertisement',
'agreement',
'air',
'amount',
'amusement',
'animal',
'answer',
'apparatus',
'approval',
'argument',
'art',
'attack',
'attempt',
'attention',
'attraction',
'authority',
'back',
'balance',
'base',
'behavior',
'belief',
'birth',
'bit',
'bite',
'blood',
'blow',
'body',
'brass',
'bread',
'breath',
'brother',
'building',
'burn',
'burst',
'business',
'butter',
'canvas',
'care',
'cause',
'chalk',
'chance',
'change',
'cloth',
'coal',
'color',
'comfort',
'committee',
'company',
'comparison',
'competition',
'condition',
'connection',
'control',
'cook',
'copper',
'copy',
'cork',
'cotton',
'cough',
'country',
'cover',
'crack',
'credit',
'crime',
'crush',
'cry',
'current',
'curve',
'damage',
'danger',
'daughter',
'day',
'death',
'debt',
'decision',
'degree',
'design',
'desire',
'destruction',
'detail',
'development',
'digestion',
'direction',
'discovery',
'discussion',
'disease',
'disgust',
'distance',
'distribution',
'division',
'doubt',
'drink',
'driving',
'dust',
'earth',
'edge',
'education',
'effect',
'end',
'error',
'event',
'example',
'exchange',
'existence',
'expansion',
'experience',
'expert',
'fact',
'fall',
'family',
'father',
'fear',
'feeling',
'fiction',
'field',
'fight',
'fire',
'flame',
'flight',
'flower',
'fold',
'food',
'force',
'form',
'friend',
'front',
'fruit',
'glass',
'gold',
'government',
'grain',
'grass',
'grip',
'group',
'growth',
'guide',
'harbor',
'harmony',
'hate',
'hearing',
'heat',
'help',
'history',
'hole',
'hope',
'hour',
'humor',
'ice',
'idea',
'impulse',
'increase',
'industry',
'ink',
'insect',
'instrument',
'insurance',
'interest',
'invention',
'iron',
'jelly',
'join',
'journey',
'judge',
'jump',
'kick',
'kiss',
'knowledge',
'land',
'language',
'laugh',
'law',
'lead',
'learning',
'leather',
'letter',
'level',
'lift',
'light',
'limit',
'linen',
'liquid',
'list',
'look',
'loss',
'love',
'machine',
'man',
'manager',
'mark',
'market',
'mass',
'meal',
'measure',
'meat',
'meeting',
'memory',
'metal',
'middle',
'milk',
'mind',
'mine',
'minute',
'mist',
'money',
'month',
'morning',
'mother',
'motion',
'mountain',
'move',
'music',
'name',
'nation',
'need',
'news',
'night',
'noise',
'note',
'number',
'observation',
'offer',
'oil',
'operation',
'opinion',
'order',
'organization',
'ornament',
'owner',
'page',
'pain',
'paint',
'paper',
'part',
'paste',
'payment',
'peace',
'person',
'place',
'plant',
'play',
'pleasure',
'point',
'poison',
'polish',
'porter',
'position',
'powder',
'power',
'price',
'print',
'process',
'produce',
'profit',
'property',
'prose',
'protest',
'pull',
'punishment',
'purpose',
'push',
'quality',
'question',
'rain',
'range',
'rate',
'ray',
'reaction',
'reading',
'reason',
'record',
'regret',
'relation',
'religion',
'representative',
'request',
'respect',
'rest',
'reward',
'rhythm',
'rice',
'river',
'road',
'roll',
'room',
'rub',
'rule',
'run',
'salt',
'sand',
'scale',
'science',
'sea',
'seat',
'secretary',
'selection',
'self',
'sense',
'servant',
'sex',
'shade',
'shake',
'shame',
'shock',
'side',
'sign',
'silk',
'silver',
'sister',
'size',
'sky',
'sleep',
'slip',
'slope',
'smash',
'smell',
'smile',
'smoke',
'sneeze',
'snow',
'soap',
'society',
'son',
'song',
'sort',
'sound',
'soup',
'space',
'stage',
'start',
'statement',
'steam',
'steel',
'step',
'stitch',
'stone',
'stop',
'story',
'stretch',
'structure',
'substance',
'sugar',
'suggestion',
'summer',
'support',
'surprise',
'swim',
'system',
'talk',
'taste',
'tax',
'teaching',
'tendency',
'test',
'theory',
'thing',
'thought',
'thunder',
'time',
'tin',
'top',
'touch',
'trade',
'transport',
'trick',
'trouble',
'turn',
'twist',
'unit',
'use',
'value',
'verse',
'vessel',
'view',
'voice',
'walk',
'war',
'wash',
'waste',
'water',
'wave',
'wax',
'way',
'weather',
'week',
'weight',
'wind',
'wine',
'winter',
'woman',
'wood',
'wool',
'word',
'work',
'wound',
'writing',
'year',
'angle',
'ant',
'apple',
'arch',
'arm',
'army',
'baby',
'bag',
'ball',
'band',
'basin',
'basket',
'bath',
'bed',
'bee',
'bell',
'berry',
'bird',
'blade',
'board',
'boat',
'bone',
'book',
'boot',
'bottle',
'box',
'boy',
'brain',
'brake',
'branch',
'brick',
'bridge',
'brush',
'bucket',
'bulb',
'button',
'cake',
'camera',
'card',
'cart',
'carriage',
'cat',
'chain',
'cheese',
'chest',
'chin',
'church',
'circle',
'clock',
'cloud',
'coat',
'collar',
'comb',
'cord',
'cow',
'cup',
'curtain',
'cushion',
'dog',
'door',
'drain',
'drawer',
'dress',
'drop',
'ear',
'egg',
'engine',
'eye',
'face',
'farm',
'feather',
'finger',
'fish',
'flag',
'floor',
'fly',
'foot',
'fork',
'fowl',
'frame',
'garden',
'girl',
'glove',
'goat',
'gun',
'hair',
'hammer',
'hand',
'hat',
'head',
'heart',
'hook',
'horn',
'horse',
'hospital',
'house',
'island',
'jewel',
'kettle',
'key',
'knee',
'knife',
'knot',
'leaf',
'leg',
'library',
'line',
'lip',
'lock',
'map',
'match',
'monkey',
'moon',
'mouth',
'muscle',
'nail',
'neck',
'needle',
'nerve',
'net',
'nose',
'nut',
'office',
'orange',
'oven',
'parcel',
'pen',
'pencil',
'picture',
'pig',
'pin',
'pipe',
'plane',
'plate',
'plough/plow',
'pocket',
'pot',
'potato',
'prison',
'pump',
'rail',
'rat',
'receipt',
'ring',
'rod',
'roof',
'root',
'sail',
'school',
'scissors',
'screw',
'seed',
'sheep',
'shelf',
'ship',
'shirt',
'shoe',
'skin',
'skirt',
'snake',
'sock',
'spade',
'sponge',
'spoon',
'spring',
'square',
'stamp',
'star',
'station',
'stem',
'stick',
'stocking',
'stomach',
'store',
'street',
'sun',
'table',
'tail',
'thread',
'throat',
'thumb',
'ticket',
'toe',
'tongue',
'tooth',
'town',
'train',
'tray',
'tree',
'trousers',
'umbrella',
'wall',
'watch',
'wheel',
'whip',
'whistle',
'window',
'wing',
'wire',
'worm',
'able',
'acid',
'angry',
'automatic',
'beautiful',
'black',
'boiling',
'bright',
'broken',
'brown',
'cheap',
'chemical',
'chief',
'clean',
'clear',
'common',
'complex',
'conscious',
'cut',
'deep',
'dependent',
'early',
'elastic',
'electric',
'equal',
'fat',
'fertile',
'first',
'fixed',
'flat',
'free',
'frequent',
'full',
'general',
'good',
'great',
'grey',
'hanging',
'happy',
'hard',
'healthy',
'high',
'hollow',
'important',
'kind',
'like',
'living',
'long',
'male',
'married',
'material',
'medical',
'military',
'natural',
'necessary',
'new',
'normal',
'open',
'parallel',
'past',
'physical',
'political',
'poor',
'possible',
'present',
'private',
'probable',
'quick',
'quiet',
'ready',
'red',
'regular',
'responsible',
'right',
'round',
'same',
'second',
'separate',
'serious',
'sharp',
'smooth',
'sticky',
'stiff',
'straight',
'strong',
'sudden',
'sweet',
'tall',
'thick',
'tight',
'tired',
'true',
'violent',
'waiting',
'warm',
'wet',
'wide',
'wise',
'yellow',
'young',
'awake',
'bad',
'bent',
'bitter',
'blue',
'certain',
'cold',
'complete',
'cruel',
'dark',
'dead',
'dear',
'delicate',
'different',
'dirty',
'dry',
'false',
'feeble',
'female',
'foolish',
'future',
'green',
'ill',
'last',
'late',
'left',
'loose',
'loud',
'low',
'mixed',
'narrow',
'old',
'opposite',
'public',
'rough',
'sad',
'safe',
'secret',
'short',
'shut',
'simple',
'slow',
'small',
'soft',
'solid',
'special',
'strange',
'thin',
'white',
'wrong'
];
var phraseList = [
  "ADDRESS BOOK",
  "AFTER-SHAVE LOTION",
  "BOOKSHELF",
  "BEANBAG CHAIR",
  "BOOKENDS",
  "CERAMIC BOWL",
  "CITRUS-SCENTED SHOWER GEL",
  "ELECTRIC TOOTHBRUSH",
  "FISHING TACKLE BOX",
  "HOME OFFICE",
  "JEWEL BOX",
  "LAVA LAMP",
  "LINEN NAPKINS",
  "MOUSEPAD",
  "OAK CHINA CABINET",
  "POLISHING WAX",
  "PENS AND PENCILS",
  "PHOTO ALBUM",
  "PROFICIENTLY DISPLAYED AWARDS",
  "PRUNING SHEARS",
  "RECLINING LOUNGE CHAIR",
  "SHAMPOO & CONDITIONER",
  "STURDY TABLE",
  "WINDOW SCREENS",
  "WOODEN TABLE",
  "CAPTAIN HOOK LINE AND SINKER",
  "EATING AN OLIVE OYL",
  "GENE POOL PARTY",
  "HOSPITAL BED IN A BAG",
  "JOE COCKER SPANIEL",
  "KNOCKOUT PUNCH BOWL",
  "NEWS FLASH GORDON",
  "PICK UP SPEED LIMIT",
  "ULTRAVIOLET RAY ROMANO",
  "WATER MAIN ATTRACTION",
  "WELCOME BACK TO THE FUTURE",
  "BABBITT",
  "CAT'S CRADLE",
  "JANE EYRE",
  "THE BIG SLEEP",
  "THE SCARLET LETTER",
  "THE HOUSE OF MIRTH",
  "THE SOUTH BEACH DIET",
  "AN AMERICAN IN PARIS",
  "CASABLANCA",
  "SOUTH PACIFIC",
  "THE BLOB",
  "THE DIRTY DOZEN",
  "ALICE FLO VERN & MEL",
  "BONANZA",
  "BULL THE BAILIFF",
  "DON JOHNSON STARS IN MIAMI VICE",
  "F TROOP",
  "HOWARD & MARION CUNNINGHAM",
  "HAWAII FIVE-O",
  "MARCIA! MARCIA! MARCIA!",
  "MIAMI VICE",
  "A SIDE TRIP TO OXFORD UNIVERSITY",
  "A CRUISE TO THE ISLAND",
  "ACT OF CONGRESS",
  "BONFIRE",
  "BIG BASH",
  "CARIBBEAN VACATION",
  "CATAMARAN SAILING CRUISE",
  "CINCO DE MAYO",
  "CATERED PARTY",
  "DAZZLING SUNSET",
  "FAMILY REUNION",
  "FISHING TOURNAMENT",
  "FORMAL DINNER",
  "HARBOR CRUISE",
  "HIGH SCHOOL REUNION",
  "HOLIDAY PARADE",
  "INDEPENDENCE DAY",
  "INTERNATIONAL FLIGHT",
  "LEAP YEAR",
  "LOS ANGELES MARATHON",
  "MARRIAGE CEREMONY",
  "MEMORIAL DAY",
  "OPENING NIGHT",
  "OPEN HOUSE",
  "PIVOTAL MOMENT",
  "PRESIDENTIAL DEBATE",
  "PRIVATE TOUR",
  "REEF DIVING",
  "RUNNING A MARATHON",
  "SALTWATER FISHING TRIP",
  "SCHOOL CHRISTMAS PAGEANT",
  "SPRING WHITE SALE",
  "SUNNY AFTERNOON",
  "TOURING THE WINDY CITY",
  "TRAVEL EXPO",
  "UNFORGETTABLE VACATION",
  "A CRUISE THROUGH GLACIER BAY",
  "ALL-EXPENSES PAID VACATION",
  "ANNUAL MEETING",
  "ANNUAL SALE",
  "BOARDROOM MEETING",
  "BUSINESS CONVENTION",
  "CAMPING ROAD TRIP",
  "CARIBBEAN GETAWAY",
  "COMIC BOOK CONVENTION",
  "DARING PARACHUTE JUMP",
  "DOG DAYS OF SUMMER",
  "GRAND TOUR",
  "HARBOR CRUISE",
  "HOLIDAY WEEKEND",
  "HUMID WEATHER",
  "IDEAL VACATION",
  "INDEPENDENCE DAY",
  "INVIGORATING WALK",
  "JOB FAIR",
  "OCEAN-VIEW DINING",
  "PRIVATE TOUR",
  "SAILBOAT RACE",
  "SANDSTORM",
  "SIGHTSEEING CRUISE",
  "SPELLING BEE",
  "SHOWS WITH SPECTACULAR STUNTS",
  "SUNNY WARM WEEKEND",
  "STATE DINNER",
  "SUMMER VACATION",
  "WATERFRONT DINING",
  "WILD-GOOSE CHASE",
  "GODFATHER & GODMOTHER",
  "PARIS AND NICKY HILTON",
  "WILL & WILLOW SMITH",
  "EEYORE & TIGGER",
  "EBENEZER SCROOGE",
  "FRED FLINSTONE",
  "HERCULES",
  "HOMER SIMPSON",
  "JACOB MARLEY",
  "NICK FURY",
  "OLD KING COLE",
  "SANTA'S ELVES",
  "THE INCREDIBLE HULK",
  "THE GREEN LANTERN",
  "TOP CAT",
  "TWEEDLEDUM",
  "THE CAT IN THE HAT",
  "VEGAS VIC",
  "THE PREHISTORIC CITY OF BEDROCK",
  "AMERICAN CHEDDAR CHEESE",
  "BAKED FRUIT COMPOTE",
  "BEAN DIP",
  "BAGLES AND LOX",
  "BEANS & CORNBREAD",
  "BOTTLED WATER",
  "BUFFALO BURGER",
  "BUTTERHEAD LETTUCE",
  "BASIL LEAVES",
  "CHICKEN QUESADILLAS",
  "CELERY ROOT SALAD",
  "CHOCOLATE SYRUP",
  "COOL TREATS",
  "CHEESE PIZZA",
  "CHOCOLATE TOFFEE",
  "CREAMY RICOTTA CHEESE",
  "CHICKEN SALAD",
  "CHOCOLATE MOUSSE",
  "DEEP-DISH PIZZA",
  "DELICIOUS CUISINE",
  "DELI SANDWICH",
  "DEEP-DISH PEACH PIE",
  "EAR OF CORN",
  "EMPANADAS",
  "ENGLISH TOFFEE",
  "FRESH FRUIT PLATTER",
  "FRESH PARSNIPS",
  "FRESH PINEAPPLE JUICE",
  "FRIED SEAFOOD PLATTER",
  "FRUIT COCKTAIL",
  "FRENCH FRIES",
  "GALA APPLES",
  "GREEN TURTLE SOUP",
  "GREEN CORN TAMALES",
  "GRANDMA'S FRUITCAKE",
  "HOMEMADE PASTA",
  "HABANERO SAUCE",
  "HAWAIIN FEAST",
  "HUEVOS RANCHEROS",
  "JUICY PINEAPPLE",
  "KOSHER SALT",
  "KEY LIME PIE",
  "LEMON-GARLIC CHICKEN",
  "LEMON DROPS",
  "LEMON POPPY SEED MUFFINS",
  "LIVER DUMPLINGS",
  "MILK CHOCOLATE BAR",
  "MINCEMEAT PIE",
  "NACHOS SUPREME",
  "OKRA SALAD",
  "ORGANIC BRAZIL NUTS",
  "OVEN-FRIED CHICKEN",
  "OYSTERS ON THE HALF SHELL",
  "PASTA WITH PARMESAN CHEESE",
  "PEACH TEA",
  "PAN GRAVY",
  "POACHED PARED FRUIT",
  "PEPPERMINT CANDY CANE",
  "RED VELVET CAKE",
  "RIPE BANANA'S",
  "RHUBARB PIE",
  "SALAD VEGETABLES",
  "SAUSAGE AND POTATOES",
  "SEARED PORK",
  "SHEPHERD'S PIE",
  "SEAFOOD TETRAZZINI",
  "SKINNED TANGELO",
  "SMOKED HAM",
  "SMOKED TROUT",
  "SPICY COCKTAIL SAUCE",
  "SEEDLESS WATERMELON",
  "THIN-CRUST PIZZA",
  "TEA AND CRUMPETS",
  "THOMPSON SEEDLESS GRAPES",
  "TUNA SALAD SANDWICH",
  "VEGETABLE JUICE",
  "VEGETABLE SOUP",
  "WEDDING CAKE",
  "YELLOW BELL PEPPERS",
  "ARM WRESTLING",
  "AFTERSCHOOL ACTIVITIES",
  "A DIP IN THE POOL",
  "BALLOON ANIMALS",
  "BELLY DANCING",
  "CATHCHING A WAVE",
  "CROSS-COUNTRY SKIING",
  "JOUSTING",
  "KAYAK POLO",
  "KNIGHT BISHOP & PAWN",
  "MOVIE STUDIO TOUR",
  "MODELING CLAY",
  "OCEAN KAYAK",
  "POKER CHIPS",
  "PLAYING ICE HOCKEY",
  "PLAYING STICKBALL",
  "RACQUETBALL",
  "ROCK CLIMBING",
  "SLOT MACHINE",
  "THUMB WRESTLING",
  "TROLLEY TOUR",
  "VIDEO POKER",
  "ALUMINUM CHEESE GRATER",
  "GLASS BOWL",
  "BAKING DISH",
  "CANNED GOODS",
  "CONICAL STRAINER",
  "CONVENTIONAL OVEN",
  "DRINKING STRAWS",
  "GRAVY LADEL",
  "INSULATED TEAPOT",
  "LEMON AND LIME SQUEEZER",
  "STAND MIXER",
  "ARLINGTON HOUSE",
  "BUNKER HILL MONUMENT",
  "CAPITOL HILL",
  "CIRCUS CIRCUS",
  "DENALI NATIONAL PARK",
  "FREMONT STREET",
  "GREAT SAND DUNES NATIONAL PARK",
  "HOOVER DAM",
  "JUDICIARY SQUARE",
  "LIBERACE MUSEUM",
  "LUXOR'S PYRAMID",
  "MADISON SQUARE GARDEN",
  "MEMORIAL BRIDGE",
  "MUSCLE BEACH",
  "NATIONAL ARBORETUM",
  "NATIONAL GALLERY OF ART",
  "NATIONAL MALL",
  "PENN STATION",
  "PRAGUE CASTLE",
  "RADIO CITY MUSIC HALL",
  "STATUE OF LIBERTY",
  "ST. PETER'S SQUARE",
  "THE CAPITOL ROTUNDA",
  "THE CHURCHILL HOTEL",
  "THE GETTY CENTER",
  "TIDAL BASIN",
  "UNIVERSAL STUDIOS HOLLYWOOD",
  "WALT DISNEY WORLD",
  "WESTMINSTER ABBEY",
  "ACORN WORM",
  "AFRICAN VIOLET",
  "AMERICAN ALLIGATOR",
  "ARCTIC FOX",
  "AFRICAN ELEPHANT",
  "ANACONDA",
  "AUSTRALIAN SHEPHERD",
  "BARRACUDA",
  "BOLL WEEVIL",
  "BORDER TERRIER",
  "BROWN BEAR",
  "CANAAN DOG",
  "CHERRY BLOSSOMS",
  "CHOCOLATE LAB",
  "DALMATIAN",
  "EELS & STINGRAYS",
  "EVERGREEN TREE",
  "FRUIT TREE",
  "LONG-LEGGED FLAMINGO ",
  "GIANT SCHNAUZER",
  "GREAT WHITE SHARK",
  "GREYHOUND",
  "IGUANA",
  "MINIATURE SCHNAUZER",
  "MOOSE & CARIBOU",
  "POMERANIAN",
  "PUFFIN",
  "RED POPPY",
  "SCARLET OAK",
  "SIBERIAN HUSKY",
  "TALL ELM TREES",
  "TAMED LIONS",
  "THE FAMILY PET",
  "SQUIRREL MONKEY",
  "WHIPPET",
  "WOOD THRUSH",
  "COLORFUL FISH",
  "DACHSHUNDS",
  "ALL ABOUT EVE",
  "ANGELS & DEMONS",
  "A BEAUTIFUL MIND",
  "BACK TO THE FUTURE",
  "CITY SLICKERS",
  "PLANET OF THE APES",
  "THE TALENTED MR. RIPLEY",
  "ATTORNEY GENERAL",
  "ARCHIVIST",
  "BRAIN SURGEON",
  "CHEMIST",
  "COURT REPORTER",
  "DRIVING INSTRUCTOR",
  "JUDGE",
  "LAWYER",
  "LUMBERJACK",
  "MUSIC TEACHER",
  "PERSONAL TRAINER",
  "PUBLIC DEFENDER",
  "RECREATION WORKER",
  "WEBMASTER",
  "ARABIAN SEA",
  "ALBANY NEW YORK",
  "ALLEGHENY MOUNTAINS",
  "BOULDER CITY NEVADA",
  "BRITISH COLUMBIA",
  "BUFFALO NATIONAL RIVER",
  "CAPITAL BELTWAY",
  "C & O CANAL",
  "DENVER COLORADO",
  "EMBASSY ROW",
  "FAIRBANKS ALASKA",
  "FAIRBANKS & KETCHIKAN",
  "GUATEMALA",
  "GREENLAND & ICELAND",
  "HAIGHT-ASHBURY",
  "HARLEM RIVER",
  "LAKE ERIE",
  "LAKE MICHIGAN",
  "LOS ANGELES",
  "LOUISVILLE KENTUCKY",
  "LOWER MANHATTAN",
  "MALIBU",
  "MARYLAND",
  "MONTANA",
  "MONTGOMERY ALABAMA",
  "NANTUCKET SOUND",
  "NEW BRUNSWICK CANADA",
  "NEWARK NEW JERSEY",
  "NEW YORK CITY",
  "OHIO DRIVE",
  "OHIO RIVER",
  "PADRE ISLAND",
  "PARK AVENUE",
  "PORTLAND OREDON",
  "SEATTLE WASHINGTON",
  "TIMES SQUARE",
  "TAMPA FLORIDA",
  "THE BAHAMAS",
  "OTTAWA CANADA",
  "PENNSYLVANIA AVENUE",
  "POTOMAC RIVER",
  "SAINT LAWRENCE RIVER",
  "SOUTHEASTERN FLORIDA",
  "SUNNY CALIFORNIA",
  "THE CITY OF CAMBRIDGE",
  "UPPER WEST SIDE",
  "VANCOUVER",
  "VENICE ITALY",
  "ABSENTEE VOTERS",
  "AMATUER ATHLETES",
  "ARCHBISHOP & CARDINAL",
  "AQUARIANS & VIRGOS",
  "AWARD NOMINEES",
  "ADORING FANS",
  "AIRLINE PASSENGERS",
  "BRIDE & GROOM",
  "CAR OWNERS",
  "CELEBRITY CHEFS",
  "COMMANDO SQUAD",
  "COLLEGE BUDDIES",
  "DYNAMIC DUO",
  "FRIENDLY LOCALS",
  "FULL-TIME EMPLOYEES",
  "FAN CLUB",
  "FLYING ACROBATS",
  "FEDERAL EMPLOYEES",
  "FRIENDS IN HIGH PLACES",
  "GOLD BUYERS",
  "GYM MEMBERS",
  "HOLLYWOOD LEGENDS",
  "NOTRE DAME'S FIGHTING IRISH",
  "OFFENSIVE & DEFENSIVE PLAYERS",
  "PILGRIMS",
  "POLITICIANS",
  "PROFESSIONAL SURFERS",
  "PLAYWRIGHTS",
  "RELIABLE WITNESSES",
  "ROOTING SECTION",
  "SINGERS & DANCERS",
  "SOCIAL CLIMBERS",
  "STRING QUARTET",
  "SUPREME COURT",
  "SMILING CHILDREN",
  "TOP PLAYERS",
  "TOUGH GUYS",
  "TEEN DRIVER",
  "THE ARMY",
  "TARGET AUDIENCE",
  "UPPER ECHELON",
  "U.S. SENATE",
  "VOLUNTEER FIREMEN",
  "VOLUNTEER FIREFIGHTERS",
  "YOUNG HOPEFULS",
  "ALTAR BOY",
  "ALTAR GIRL",
  "BICYCLE MESSENGER",
  "BYSTANDER",
  "BIOGRAPHER",
  "BUSYBODY",
  "CAMPAIGN MANAGER",
  "CERTIFIED TECHNICIAN",
  "CHIEF OF STAFF",
  "COCKTAIL WAITRESS",
  "COLONIAL HISTORY BUFF",
  "CIA AGENT",
  "CIVIL WAR BUFF",
  "DADDY'S LITTLE GIRL",
  "DOUBTING THOMAS",
  "EXPERT ARCHER",
  "FIRST BASEMAN",
  "FBI AGENT",
  "FIRST LADY",
  "FOLK HERO",
  "GRAFFITI ARTIST",
  "GREAT GRANDCHILD",
  "GOLD MEDAL WINNER",
  "GYMNAST",
  "HIGH ROLLER",
  "JACKPOT WINNER",
  "JUNIOR LIFEGUARD",
  "JUNIOR SENATOR",
  "JOURNALISM STUDENT",
  "LONGTIME SUBSCRIBER",
  "LAW STUDENT",
  "LEFT FIELDER",
  "MEDICAL DOCTOR",
  "MATRON OF HONOR",
  "NATURAL REDHEAD",
  "OLYPMIC SWIMMER",
  "OLD FRIEND",
  "PLATOON LEADER",
  "PUBLIC SPEAKER",
  "SCHOOL COUNSELOR",
  "SOUTHPAW",
  "SENIOR OFFICIAL",
  "STAGE MOTHER",
  "STAR PERFORMER",
  "SPEAKER OF THE HOUSE",
  "STEADY BOYFRIEND",
  "TRAINED ATHLETE",
  "WOODCARVER",
  "WET BLANKET",
  "A GOOD FIT",
  "A GREAT BUY",
  "AHEAD OF THE GAME",
  "ALL OPERATORS ARE BUSY",
  "AS RED AS A BEET",
  "AVOID THE PITFALLS",
  "A GRIPPING PAGE TURNER",
  "ALL KINDS OF THINGS TO DO",
  "BIG-CTY DIVERSITY",
  "BACK TO SQUARE ONE",
  "BACK TO BASICS",
  "BONJOUR!",
  "BUILT TO LAST",
  "COAST-TO-COAST",
  "COMING UNGLUED",
  "CALL FOR DIRECTIONS",
  "COMING ON LIKE GANGBUSTERS",
  "CLOSED FOR RENOVATIONS",
  "CULTURAL CENTER OF THE COUNTRY",
  "DO YOU SPEAK FRENCH?",
  "DRAWING A BLANK",
  "DON'T SPOIL YOUR DINNER",
  "EXPLAIN YOURSELF",
  "FADING AWAY",
  "FAMILY FUN",
  "FALL IN LOVE WITH THIS CITY",
  "FIRE UP THE GRILL",
  "FULL-BODIED FLAVOR",
  "GIVE ME A HINT",
  "GOING HALFWAY",
  "GOING THE DISTANCE",
  "GROWING UP",
  "HAVING A GREEN THUMB",
  "HAIL TO THE CHIEF",
  "HAVE A BITE TO EAT",
  "HERE WE GO AGAIN",
  "I WAS BORN READY",
  "IN THE LIMELIGHT",
  "IT NEVER EVEN CROSSED MY MIND",
  "IT'S ALL IN A DAY'S WORK",
  "I'VE GOT A HUNCH",
  "IT'S A DIRTY SHAME",
  "I'VE LEARNED MY LESSON",
  "JUST CHILLIN'",
  "KEEP YOUR COOL",
  "KEEP YOUR NOSE CLEAN",
  "LAY IT ON THICK",
  "MIX AND MATCH",
  "MINT CONDITION",
  "NEVER SAY NEVER",
  "NEVER IN MY WILDEST DREAMS",
  "ONCE IN A BLUE MOON",
  "OPEN UP A CAN OF WORMS",
  "PICTURE THIS",
  "PICK A CARD ANY CARD",
  "PURE COINCIDENCE",
  "RAISING CAIN",
  "RAKE OVER THE COALS ",
  "READY WHEN YOU ARE",
  "RETURN TO PARADISE",
  "SEASON TO TASTE",
  "SEATING IS LIMITED",
  "SHAKEN NOT STIRRED",
  "SHARE AND SHARE ALIKE",
  "STOP BUILDING CASTLES IN THE SKY",
  "STANDING ROOM ONLY",
  "SOME ASSEMBLY REQUIRED",
  "SWEET SIXTEEN AND NEVER BEEN KISSED",
  "THE TRUTH SHALL SET YOU FREE",
  "TAKE CARE",
  "TIME FOR MIRACLES",
  "THANKS A MILLION",
  "THEY NEVER KNEW WHAT HIT THEM",
  "THROWING YOUR MONEY AROUND",
  "TWO OF A KIND",
  "UP-AND-COMING",
  "WALK IT OFF",
  "WITHOUT SPENDING AN ARM & A LEG",
  "WISH YOU WERE HERE",
  "WORK SMARTER NOT HARDER",
  "WAY TO GO!",
  "YOU'RE PUSHING MY BUTTONS",
  "YOUR MESSAGE HAS BEEN SENT",
  "YOUR HEART IS IN THE RIGHT PLACE",
  "YOU TOOK THE WORDS RIGHT OUT OF MY MOUTH",
  "ZOOM IN",
  "A FARAWAY LAND",
  "ABANDONED WAREHOUSE",
  "ACCREDITED COLLEGE",
  "ALOHA STATE",
  "AMAZON RAIN FOREST",
  "ARTIST'S LOFT",
  "A CITY WITH GREAT HISTORY",
  "ART MUSEUM",
  "BILINGUAL CITY",
  "BROWNSTONE",
  "BUNGALOW",
  "BUSTLING CITY",
  "CAMPGROUND",
  "CORNER NEWSSTAND",
  "CAPTIVATING CITY",
  "CITY THAT'S A PLEASURE FOR EVERYONE",
  "CULINARY SCHOOL",
  "CONVENIENT LOCATION",
  "DENSE TROPICAL JUNGLE",
  "DELUXE SUITE",
  "DEPARTMENT STORE",
  "FABULOUS ROADSIDE ATTRACTION",
  "FACTORY OUTLET MALL",
  "FAMOUS RESTAURANT",
  "FOOD COURT",
  "FRENCH BISTRO",
  "GAS STATION",
  "GIANT TOY STORE",
  "GOLF CLUBHOUSE",
  "GUESTHOUSE",
  "INDOOR GARDEN",
  "INLAND WATERWAY",
  "KOREAN BARBECUE RESTAURANT",
  "LARGE METROPOLITAN AREA",
  "LOG HOUSE",
  "LUSH GREEN FOREST",
  "MOLOKONI",
  "MIDDLE SCHOOL",
  "OVAL OFFICE",
  "PAVED DRIVEWAY",
  "PICNIC PAVILION",
  "PRIVATE GYM",
  "PRIVATE RESIDENCE",
  "R.F.K. STADIUM",
  "ROMANTIC SPOT",
  "REFLECTING POOL",
  "SCULPTURE GARDEN",
  "SPORTING GOODS STORE",
  "SEAPORT DISTRICT",
  "THE CAPITAL OF ITALY",
  "THE CAPITAL OF GERMANY",
  "TROPICAL PARADISE",
  "TROUT STREAM",
  "THE WEST WING",
  "TINSELTOWN",
  "UPSCALE HOTEL",
  "VIDEO ARCADE",
  "VICTORIAN HOME",
  "WEEDING CHAPEL",
  "WHITE SAND BEACH",
  "WORLD'S LONGEST STREET",
  "WRAPAROUND PORCH",
  "WHITE HOUSE LAWN",
  "WINE COUNTRY",
  "ACQUATIC GARDENS",
  "AGE-OLD CHURCHES",
  "ART GALLERY",
  "ANCIENT TEMPLES",
  "BOTANICAL GARDENS",
  "BACK ALLEY",
  "BOUTIQUE",
  "BREATHTAKING CANADIAN CITY",
  "BUSY STREETS",
  "COFFEE SHOPS",
  "CAPITAL CITY OF FRANCE",
  "CHURCHES AND SYNONGOGUES",
  "COLLEGES & UNIVERSITIES",
  "COASTAL MEADOWS",
  "CORNER OFFICE",
  "COVERED PORCH",
  "DIVERSE RESTAURANTS",
  "FLAWLESS SANDY BEACHES",
  "GREAT RESTAURANTS",
  "GOTHIC CATHEDRALS",
  "HUMID LOWLAND JUNGLES",
  "HISTORICAL SITES",
  "IVY LEAGUE COLLEGES",
  "MARINE BARRACKS",
  "MUSEUM MILE",
  "NARROW COBBLESTONE STREETS",
  "NEOCLASSICAL BUILDINGS",
  "NIGHTCLUBS",
  "PLAYGROUND",
  "ROW HOUSES",
  "STATE CAPITALS",
  "SCHOOL CAFETERIA",
  "TACO STAND",
  "THE APPIAN WAY",
  "THE GULF COAST",
  "THE SKYDECK AT WILLIS TOWER",
  "TRIBAL LANDS",
  "TRENDY SHOPS",
  "WHITEWASHED HOTELS",
  "WORLD-FAMOUS PARKS & ATTRACTIONS",
  "AIR FORCE ONE",
  "AMERICAN STOCK EXCHANGE",
  "BASKETBALL STAR ALLEN IVERSON",
  "BEN STILLER",
  "BEN AFFLECK",
  "BUZZ ALDRIN",
  "BOSTON BRUINS",
  "BILL OF RIGHTS",
  "BUGSY SIEGEL",
  "CALGARY FLAMES",
  "COMPOSER JOHANN SEBASTIAN BACH",
  "ELI MANNING",
  "FREDERICK DOUGLASS",
  "JAMES EARL JONES",
  "JEREMY SISTO",
  "JIMMY FALLON",
  "KEVIN DILLON",
  "LARRY BIRD",
  "LANCE BURTON",
  "MARVEL COMICS",
  "MARK HARMON",
  "MONTY PYTHON",
  "MEL BROOKS",
  "MICHELLE OBAMA",
  "MONA LISA",
  "NEIL PATRICK HARRIS",
  "NEIL SIMON",
  "PRINCE HARRY",
  "PURDUE UNIVERSITY",
  "RYAN PHILLIPPE",
  "SAN FRANCISCO GIANTS",
  "SINGER TIM MCGRAW",
  "SURVIVOR HOST JEFF PROBST",
  "THE VELVET UNDERGROUND",
  "THE BRADFORD EXCHANGE",
  "THE ROLLING STONES",
  "THE YANKEES",
  "TIKI BARBER",
  "U.S. AIR FORCE ACADEMY",
  "U.S. DEPARTMENT OF EDUCATION",
  "UNITED STATES COAST GUARD",
  "UTAH JAZZ",
  "WASHINGTON NATIONALS",
  "WASHINGTON REDSKINS",
  "ADAM & EVE",
  "BASKETBALL STAR LEBRON JAMES",
  "BOSTON RED SOX",
  "BRADLEY COOPER",
  "CIRQUE DU SOLEIL",
  "DENZEL WASHINGTON",
  "NATIONAL BASKETBALL LEAGUE",
  "ORVILLE & WILBUR WRIGHT",
  "UNIVERSITY OF NOTRE DAME",
  "A POCKET FULL OF RYE",
  "A PICTURE IS WORTH A THOUSAND WORDS",
  "CALL ME ISHMAEL",
  "GOOD GRIEF CHARLIE BROWN",
  "JACK BE QUICK",
  "LITTLE B0-PEEP HAS LOST HER SHEEP",
  "LONDON BRIDGE IS FALLING DOWN",
  "CHIP CLIP",
  "CHEERS AND JEERS",
  "GO WITH THE FLOW",
  "HUSTLE & BUSTLE",
  "PIE IN THE SKY",
  "BUCKINGHAM & CAEASAR'S PALACE",
  "ECONOMY & BUSINESS CLASS",
  "EYE & BOTTLE OPENER",
  "MONEY & CARRYOUT ORDER",
  "PEANUT & TURTLE SHELL",
  "POWER & CREDIBLE SOURCE",
  "RECORD & SOUP LABEL",
  "WEDDING & DAILY PLANNER",
  "ALL-STAR CAST",
  "CAMERAS ROLLING",
  "DOCUMENTARY FILM",
  "FILM REVIEW",
  "MAY I HAVE A DRUMROLL PLEASE?",
  "MUSICAL COMEDY",
  "OPEN AUDITION",
  "SEASON FINALE",
  "SINGING SENSATION",
  "STAGE ACTORS",
  "I DID IT MY WAY",
  "ONE FOR THE MONEY TWO FOR THE SHOW",
  "DEDICATED TO THE ONE I LOVE",
  "A FRIENDLY REMINDER",
  "A PLEASANT SURPRISE",
  "A BRISK PACE",
  "A SHARP PENCIL",
  "ACHES & PAINS",
  "AMERICAN FLAG",
  "ARCHERY",
  "APLINE GLACIERS",
  "ASSEMBLY LINE",
  "AIRCRAFT CARRIER",
  "AN AMAZING VIEW OF THE SKYLINE",
  "BRIGHT BLUE SKY",
  "BATTLESHIP",
  "BATTING HELMET",
  "BIRTHDAY PRESENT",
  "BIG DECISION",
  "BLUE RIBBON",
  "BOOKMARK",
  "CORNCOB PIPE",
  "CALYPSO MUSIC",
  "CHAINSAW",
  "COLOR PRINTER",
  "CLASSICAL MUSIC",
  "COMPUTER SOFTWARE",
  "DAZZLING NIGHTLIFE",
  "DESIGNER LUGGAGE",
  "DOTTED LINE",
  "DOUBLE COUPONS",
  "ENGRAVED INVITATIONS",
  "EYELASH CURLER",
  "ENGAGING CONVERSATION",
  "EYEBROW PENCIL",
  "FIGHTER JET",
  "FLOODLIGHT",
  "FAVORABLE CLIMATE",
  "FINE DINING",
  "FLEETING MOMENT",
  "FOND MEMORIES",
  "FREIGHT ELEVATOR",
  "FUN HOBBY",
  "GOOD PUBLICITY",
  "GUILTY PLEASURE",
  "GOOD JUDGMENT",
  "GOOD LUCK CHARM",
  "GREAT PERSONALITY",
  "HARDBACK BOOK",
  "HEALING MASSAGE",
  "HD DIGITAL CAMERA",
  "HOODED SWEATSHIRT ",
  "HUMBLE HONOR",
  "ICY SNOWBANK",
  "JEAN JACKET",
  "JUNIOR COLLEGE FOOTBALL",
  "JUMBO SNOWFLAKES",
  "LEADING NATIONAL BRANDS",
  "LEISURE SUIT",
  "LIGHTING DISPLAYS",
  "LINEN HANKERCHIEF",
  "LIFE SAVINGS",
  "LOFT BED",
  "LUNCH MONEY",
  "LIFETIME WARRANTY",
  "MILD WEATHER",
  "MAGAZINE ARTICLE",
  "MEMBERSHIP DUES",
  "MINIMUM WAGE",
  "MODERN ART",
  "MUD FLAPS",
  "MATH QUIZ",
  "MONUMENTS",
  "NATURAL ABILITY",
  "NATURAL HABITAT",
  "NAVAL FLEET",
  "OVERNIGHT DELIVERY",
  "PERFECT REPORT CARD",
  "PIRATE BOOTY",
  "PADLOCK",
  "PILOTS LICENSE",
  "PLEASANT CONVERSATION",
  "PRETTY SMILES",
  "PRESIDENTIAL SEAL",
  "QUICK RUNDOWN",
  "RADIO STATION",
  "RADIO TUNER",
  "RESORT VACATION",
  "SADDLEBAG",
  "SAVINGS ACCOUNT",
  "SCAFFOLD",
  "SENATORIAL GAVEL",
  "SPARE KEY",
  "SPARKLING SKYLINE",
  "SPECTACULAR SUNSET",
  "SUNNY FORECAST",
  "STARTING REVELATION",
  "SUBSTANTIVE ARGUMENT",
  "SUBWAY SYSTEM",
  "TEMPTING OFFER",
  "TREE TRUNK",
  "THE CONSTITUTION",
  "THE SOOTHING SOUND OF THE WAVES",
  "TIKI STATUE",
  "THUNDEROUS ROUND OF APPLAUSE",
  "TOLL-FREE CUSTOMER SERVICE NUMBER",
  "TOTEM POLE",
  "TRENDY HAIRSTYLE",
  "UNIQUE URBAN EXPERIENCE",
  "UNIQUE BUILDINGS",
  "UP TEMPO",
  "VACATION OF MY DREAMS",
  "WINNING TICKET",
  "WINNING STREAK",
  "WRAPPED PRESENTS",
  "WARM AND SUNNY CLIMATE",
  "WARM WEATHER",
  "WATER SLIDE",
  "WITCH'S POTION",
  "WOODEN TOY BOX",
  "WOODEN UKULELE",
  "ACTION FIGURES",
  "ACRES OF LAND",
  "ADVERSE CONDITIONS",
  "ALKALINE BATTERIES",
  "AMAZING HIKES",
  "ARCHITECTURAL TREASURES",
  "BLUE SKIES",
  "BUSINESS HOURS",
  "CARTILAGE & VERTEBRAE",
  "COLORFUL EMBROIDERED BLOUSES",
  "DIVERSE CULTURES",
  "EMERGENCY SUPPLIES",
  "ENGRAVED INVITATIONS",
  "FOND MEMORIES",
  "FUNKY GADGETS",
  "FINGERPRINTS",
  "HOLIDAY ORNAMENTS",
  "HOT HUMID SUMMERS",
  "LUCKY NUMBERS",
  "MAJOR ISSUES",
  "MASKING TAPE",
  "MEOWS & WOOFS",
  "METAL SCULPTURES",
  "MONUMENTS",
  "ON-CAMPUS ACTIVITIES",
  "OUTDOOR ACTIVITIES",
  "ROSY CHEEKS",
  "SHORT STORIES",
  "SOLAR PANELS",
  "STRIKING SIMILARITIES",
  "SKYSCRAPERS",
  "STRENGTHS AND WEAKNESSES",
  "STONY CORAL REEFS",
  "SUMMER WARDROBE",
  "STRICT GUIDELINES",
  "SUN-KISSED CHEEKS",
  "TICKETS TO A ROCK CONCERT",
  "TABLE MANNERS",
  "TICKETS TO A MIAMI HEAT GAME",
  "UNIQUE BUILDINGS",
  "UNIQUE ISLANDS",
  "WARM SUNSHINE",
  "WATERFALLS",
  "A CHRISTMAS CAROL",
  "ALICE'S ADVENTURES IN WONDERLAND",
  "ALL THAT JAZZ ",
  "DETROIT FREE PRESS",
  "GOOD HOUSEKEEPING",
  "GQ MAGAZINE",
  "I KNOW WHY THE CAGED BIRD SINGS",
  "JERSEY BOYS",
  "ROLLING STONE MAGAZINE",
  "THE ARIZONA REPUBLIC",
  "THE WASHINGTON POST",
  "THE WORLD ALMANAC FOR KIDS",
  "THE THREE LITTLE PIGS",
  "FAMILY GUY",
  "HOW I MET YOUR MOTHER",
  "MEN OF A CERTAIN AGE",
  "SO YOU THINK YOU CAN DANCE",
  "THE CLEVELAND SHOW",
  "THE REAL HOUSEWIVES OF NEW YORK CITY",
  "ATTENDING WIMBLEDON",
  "BUYING A NEW COAT",
  "BUYING TACOS FROM A STREET VENDOR",
  "COOKING FRESHLY CAUGHT FISH",
  "COLLECTING SEASHELLS",
  "DANCING IN THE SAND",
  "DIGGING MY TOES IN THE SAND",
  "DISCOVERING CANADIAN ART",
  "DUSTING MY DESK",
  "EATING RAW VEGETABLES",
  "ENJOYING A ROMANTIC VIEW OF THE CITY",
  "ENJOYING THE VIEW FROM NOB HILL",
  "FEEDING THE DUCKS AT THE PUBLIC GARDEN",
  "FLYING TO A FOREIGN COUNTRY",
  "GOING TO THE BALLET",
  "GARGLING WITH MOUTHWASH",
  "GETTING GOOSE BUMPS",
  "GOING FOR A BIKE RIDE",
  "GOING TO THE GYM",
  "GOING TO A NIGHTCLUB",
  "HAILING A CAB",
  "KAYAKING IN THE BAY",
  "LEARNING TO HULA",
  "LISTENING TO THE CHIMES OF BIG BEN",
  "PAINTING A PICTURE",
  "PAINTING THE HOUSE",
  "PANNING FOR GOLD",
  "RELAXING POOLSIDE",
  "REMODELING THE KITCHEN",
  "SENDING THANK YOU NOTES",
  "SHOPPING IN SOHO",
  "SNORKELING IN CLEAR BLUE WATER",
  "STAYING IN A BEACH BUNAGLOW",
  "SCRUBBING THE FLOOR",
  "SPEAKING FRENCH AND ENGLISH",
  "STANDING IN MY BARE FEET",
  "SHAKING HANDS WITH MINNIE MOUSE",
  "SHOPPING AT THE ANTIQUE FAIR",
  "SPENDING THE DAY HIKING IN THE MOUNTAINS",
  "SEEING A MOVIE",
  "SHINING MY SHOES",
  "STANDING IN LINE",
  "SUNNING MYSELF ON THE BEACH",
  "TAKING IN AN AFTERNOON MOVIE",
  "TAKING A DAY TRIP TO KISSIMMEE",
  "TAKING IT EASY",
  "TAKING A DAY TRIP TO THE BEACH",
  "TELLING TALL TALES",
  "TOURING THE ISLAND ON HORSEBACK",
  "TRAVELING IN A SNOWMOBILE",
  "VISITING THE ZOO",
  "VISITING THE OLD ROYAL PALACE",
  "WATCHING THE HOCKEY GAME",
  "WIPING OFF MY SHOES",
  "ZOOMING DOWN A WATER SLIDE"];
var deathSayings = [
  "Nooooooo",
  "This is your fault",
  "I enjoyed being alive, you know",
  "Tell my wife... I...",
  "Good job. Really.",
  "It's fine. I guess I\'ll just hang around",
  "Meat is hung, men are hanged",
  "You had SO many chances to get this right!",
  "%&*$#!",
  "Vanna never had to deal with this...",
  "Bob Barker sez: \'Spay and neuter your pets!\'",
  "*gack*",
  "I guess you should have Googled it",
  "Well, at least the vowels were free",
  "I was one day from retirement!",
  "Life without parole doesn\'t sound so bad now",
  "Not as smart as you thought you were, huh?",
  "I\'m not mad. Just disappointed",
  "You've done so well for someone with your education level",
  "Oh, I\'m sure I\'ll be fine",
  "Go ahead. Try again. I\'m sure the next hangman will live.",
  "You\'re SO GOOD at this. Totally.",
  "It\'s okay. I\'m sure nobody else could have guessed that, either",
  "At least you mother still loves you. Probably.",
  "Is this because I didn\'t invite you to my party?",
  "It\'s all about you, huh?"
];
