window.addEventListener ?
  window.addEventListener("load", setupGame, false) :
  window.attachEvent && window.attachEvent("onload", setupGame);

var healthNumber = 5;
var hitNumber = 0;
var monsterHit = 4;
var monstersFought = []


function setupGame() {
  healthNumber = 5;
  hitNumber = 0;
  monsterHit = 4;
  $("#healthnumber").text(healthNumber);
  $(".health").css("background-color", "green").show();;
  $(".hitnumberbonus").hide();
  $("#hitnumber").text(hitNumber);
  $("#monsterhit").text(monsterHit);
  $("#d10roll").text("");
  $("#totalhit").text("");
  $("#hit").show();
  $("#win").hide();
  $("#slain").hide();
  $("#monstername").text(monsters[monsterHit-3][roll("1d"+monsters[monsterHit-3].length)])
  monstersFought = []
  monstersFought[0] = "Nothing, you loser!"
  monstersFought.push($("#monstername").text())
}


function trytohit() {
  let thisroll = roll("1d10");

  $("#d10roll").text(thisroll);

  let currentHit = thisroll + hitNumber;

  $("#totalhit").text(currentHit);


  if (currentHit >= monsterHit) {
    if (hitNumber >= 20 && monsterHit == 26) {
      $("#win").show();
      $("#hit").hide();
    } else {
      hitNumber += 1;
      monsterHit += 1;
      $("#hit"+hitNumber).show()
      $("#hitnumber").text(hitNumber);
      $("#monsterhit").text(monsterHit);
      $("#monstername").text(monsters[monsterHit-3][roll("1d"+(monsters[monsterHit-3].length-1))])
      monstersFought.push($("#monstername").text())
    }    

  } else {
    healthNumber -= 1;
    if (healthNumber == 4) {
      $("#health5").hide();
      $(".health").css("background-color", "greenyellow");
    } else if (healthNumber == 3) {
      $("#health4").hide();
      $(".health").css("background-color", "yellow");
    } else if (healthNumber == 2) {
      $("#health3").hide();
      $(".health").css("background-color", "orange");
    } else if (healthNumber == 1) {
      $("#health2").hide();
      $(".health").css("background-color", "red");
    }
    $("#healthnumber").text(healthNumber);
    if (healthNumber == 0) {     
      $(".health").hide(); 
      $("#finalmonsterhit").text(monsterHit-1);
      $("#finalmonsterslain").text(monstersFought[monstersFought.length-2]);
      $("#slain").show();
      $("#hit").hide();
    }
  }
}


function roll(str, mod = 0) {

  if (str == "-") {
      return 1;
  }

  let numRolls = Number(str.split("d")[0]);
  let diceValue = Number(str.split("d")[1]);

  let result = [];

  for (let i = 0; i < numRolls; i++) {
      result.push(Math.floor((Math.random() * diceValue) + 1))
  }

  // Sorts the array of rolls for ease of removing high/low values
  result.sort(function (a, b) {
      return a - b
  })

  if (mod == 1) {
      // Remove lowest value
      result.shift()
  } else if (mod == -1) {
      // Remove highest value
      result.pop()
  }

  let total = sumArr(result);

  return total;
}

function sumArr(arr) {
  let sum = 0;
  for (let i = 0; i < arr.length; i++) {
      sum += arr[i];
  }

  return sum;
}

const monsters = [
  [],
  [
    "Animated Armor",
    "Brass Dragon Wyrmling",
    "Brown Bear",
    "Bugbear",
    "Copper Dragon Wyrmling",
    "Crag Cat",
    "Death Dog",
    "Deinonychus",
    "Dire Wolf",
    "Dragonclaw",
    "Dread Warrior",
    "Dryad",
    "Duergar",
    "Duergar Soulblade",
    "Evil Mage",
    "Faerie Dragon (Orange)",
    "Faerie Dragon (Red)",
    "Faerie Dragon (Yellow)",
    "Feathergale Knight",
    "Female Steeder",
    "Fire Snake",
    "Firenewt Warlock of Imix",
    "Ghoul",
    "Giant Eagle",
    "Giant Hyena",
    "Giant Octopus",
    "Giant Spider",
    "Giant Strider",
    "Giant Toad",
    "Giant Vulture",
    "Gnoll Flesh Gnawer",
    "Goblin Boss",
    "Grung Wildling",
    "Guardian Portrait",
    "Half-Ogre (Ogrillon)",
    "Harpy",
    "Hippogriff",
    "Ice Toad",
    "Imp",
    "Jamna Gleamsilver",
    "Kobold Dragonshield",
    "Kobold Scale Sorcerer",
    "Kuo-Toa Whip",
    "Lion",
    "Maw Demon",
    "Nilbog",
    "Phantom Warrior",
    "Quadrone",
    "Quaggoth Spore Servant",
    "Quasit",
    "Quickling",
    "Scarecrow",
    "Sea Spawn",
    "Sildar Hallwinter",
    "Specter",
    "Spy",
    "Swarm of Quippers",
    "Thorny",
    "Thri-kreen",
    "Thri-kreen (Psionic)",
    "Tiger",
    "Vargouille",
    "Xvart Warlock of Raxivort",
    "Yuan-ti Pureblood",
    "Yusdrayl",
    "Nihilethic Zombie",
    "Bastet Temple Cat",
    "Boloti",
    "Broodiken",
    "Chernomoi",
    "Child Of The Briar",
    "Weaving Spider",
    "Dogmole",
    "Wyrmling Wind Dragon",
    "Crimson Drake",
    "Emerald Eye",
    "Eonic Drifter",
    "Erina Defender",
    "Gerridae",
    "Glass Gator",
    "Kobold Trapsmith",
    "Leshy",
    "Moss Lurker",
    "Ratfolk Rogue",
    "Rime Worm Grub",
    "Sharkjaw Skeleton",
    "Zanskaran Viper",
    "Wampus Cat"
  ],
  [
    "Allosaurus",
    "Animated Table",
    "Ankheg",
    "Aurochs",
    "Awakened Tree",
    "Awakened Zurkhwood",
    "Azer",
    "Bandit Captain",
    "Bard",
    "Berserker",
    "Black Dragon Wyrmling",
    "Black Earth Guard",
    "Black Guard Drake",
    "Blue Guard Drake",
    "Bronze Dragon Wyrmling",
    "Carrion Crawler",
    "Cave Bear",
    "Centaur",
    "Chamberlain of Zuggtmoy",
    "Crushing Wave Priest",
    "Cult Fanatic",
    "Darkling Elder",
    "Dragonwing",
    "Droki",
    "Druid",
    "Duergar Darkhaft",
    "Duergar Kavalrachni",
    "Duergar Keeper of the Flame",
    "Duergar Spy",
    "Duergar Stone Guard",
    "Duergar Xarron",
    "Eternal Flame Guardian",
    "Ettercap",
    "Faerie Dragon (Blue)",
    "Faerie Dragon (Green)",
    "Faerie Dragon (Indigo)",
    "Faerie Dragon (Violet)",
    "Fathomer",
    "Frulam Mondath",
    "Gargoyle",
    "Gelatinous Cube",
    "Ghast",
    "Giant Boar",
    "Giant Constrictor Snake",
    "Giant Crayfish",
    "Giant Elk",
    "Gibbering Mouther",
    "Githzerai Monk",
    "Gnoll Pack Lord",
    "Green Dragon Wyrmling",
    "Green Guard Drake",
    "Grick",
    "Griffon",
    "Grisha",
    "Grung Elite Warrior",
    "Guard Drake",
    "Hobgoblin Iron Shadow",
    "Howling Hatred Priest",
    "Hunter Shark",
    "Hurricane",
    "Intellect Devourer",
    "Kuo-Toa Monitor",
    "Lizardfolk Shaman",
    "Meenlock",
    "Merrow",
    "Mimic",
    "Minotaur Skeleton",
    "Myconid Sovereign",
    "Narrak",
    "Nereid",
    "Nezznar the Black Spider",
    "Nothic",
    "Ochre Jelly",
    "Ogre",
    "Ogre Zombie",
    "Orc Claw of Luthic",
    "Orc Eye of Gruumsh",
    "Orc Hand of Yurtrus",
    "Oreioth",
    "Orog",
    "Pegasus",
    "Pentadrone",
    "Peryton",
    "Plesiosaurus",
    "Polar Bear",
    "Poltergeist",
    "Priest",
    "Purple Wormling",
    "Quaggoth",
    "Quetzalcoatlus",
    "Red Guard Drake",
    "Rhinoceros",
    "Rug of Smothering",
    "Saber-Toothed Tiger",
    "Sahuagin Priestess",
    "Sea Hag",
    "Shadow Mastiff",
    "Silver Dragon Wyrmling",
    "Spined Devil",
    "Swarm of Poisonous Snakes",
    "Thayan Warrior",
    "Uthgardt Shaman",
    "Vampiric Ixitxachitl",
    "Vampiric Ixitxachitl Cleric",
    "Vegepygmy Chief",
    "Wererat",
    "Wereraven",
    "White Dragon Wyrmling",
    "White Guard Drake",
    "Wiggan Nettlebee",
    "Will-o'-Wisp",
    "Yuan-ti Broodguard",
    "Giant Ant",
    "Anubian",
    "Behtu",
    "Beli",
    "Clockwork Hound",
    "Cobbleswarm",
    "Deep One",
    "Ink Devil",
    "Doppelrat",
    "Cave Dragon Wyrmling",
    "Sea Dragon Wyrmling",
    "Void Dragon Wyrmling",
    "Paper Drake",
    "Eala",
    "Eel Hound",
    "Firegeist",
    "Folk Of Leng",
    "Gray Thirster",
    "Kobold Alchemist",
    "Kot Bayun",
    "Myling",
    "Noctiny",
    "Putrid Haunt",
    "Roachling Lord",
    "Shadhavar",
    "Shellycoat",
    "Spider Thief",
    "Tosculi Warrior",
    "Uraeus",
    "Vile Barber",
    "Vine Lord's Tendril Puppet"
  ],
  [
    "Ankylosaurus",
    "Archer",
    "Basilisk",
    "Bearded Devil",
    "Black Earth Priest",
    "Blue Dragon Wyrmling",
    "Bugbear Chief",
    "Cave Fisher",
    "Choldrith",
    "Dark Tide Knight",
    "Deathlock Wight",
    "Deep Scion",
    "Derro Savant",
    "Displacer Beast",
    "Doppelganger",
    "Dralmorrer Borngray",
    "Eternal Flame Priest",
    "Flail Snail",
    "Giant Lightning Eel",
    "Giant Scorpion",
    "Githyanki Warrior",
    "Gold Dragon Wyrmling",
    "Green Hag",
    "Grell",
    "Hell Hound",
    "Hobgoblin Captain",
    "Hook Horror",
    "Hook Horror Spore Servant",
    "Illusionist",
    "Kalka-Kylla",
    "Killer Whale",
    "Knight",
    "Leucrotta",
    "Manticore",
    "Martial Arts Adept",
    "Minotaur",
    "Mormesk the Wraith",
    "Mummy",
    "Neogi",
    "Nightmare",
    "One-Eyed Shiver",
    "Orc Red Fang of Shargaas",
    "Owlbear",
    "Pharblex Spattergoo",
    "Phase Spider",
    "Quaggoth Thonot",
    "Redcap",
    "Siren",
    "Skyweaver",
    "Slithering Tracker",
    "Spectator",
    "Swashbuckler",
    "Thurl Merosska",
    "Trapper",
    "Troglodyte Champion of Laogzed",
    "Vampiric Mist",
    "Veteran",
    "Water Weird",
    "Werewolf",
    "Wight",
    "Windharrow",
    "Winter Wolf",
    "Yakfolk Warrior",
    "Yeti",
    "Yuan-ti Malison",
    "Alseid Grovekeeper",
    "Amphiptere",
    "Arboreal Grappler",
    "Bagiennik",
    "Bearfolk",
    "Cactid",
    "Ratch",
    "Clockwork Beetle Swarm",
    "Clockwork Huntsman",
    "Mbielu",
    "Flame Dragon Wyrmling",
    "Duskthorn Dryad",
    "Far Darrig",
    "Ghoul, Darakhul",
    "Thursir Giant",
    "Gnoll Havoc Runner",
    "Goat-Man",
    "Imy-Ut Ushabti",
    "Jaculus",
    "Mahoru",
    "Millitaur",
    "Mindrot Thrall",
    "Mirager",
    "Monolith Footman",
    "Venomous Mummy",
    "Pombero",
    "Ravenfolk Warrior",
    "Night Scorpion",
    "Stygian Fat-Tailed Scorpion",
    "J'ba Fofi Spider",
    "Spire Walker",
    "Prismatic Beetle Swarm",
    "Sluagh Swarm",
    "Elvish Veteran Archer",
    "Wolf Reaver Dwarf"
  ],
  [
    "Azbara Jos",
    "Babau",
    "Banshee",
    "Barghest",
    "Black Pudding",
    "Bone Naga (Guardian)",
    "Bone Naga (Spirit)",
    "Burrowshark",
    "Chuul",
    "Chuul Spore Servant",
    "Couatl",
    "Elephant",
    "Ettin",
    "Flameskull",
    "Ghost",
    "Giant Subterranean Lizard",
    "Girallon",
    "Gnoll Fang of Yeenoghu",
    "Helmed Horror",
    "Hobgoblin Devastator",
    "Kelpie",
    "Lamia",
    "Langdedrosa Cyanwrath",
    "Lizard King/Queen",
    "Neogi Master",
    "Orc Blade of Ilneval",
    "Orc War Chief",
    "Red Dragon Wyrmling",
    "Shadow Demon",
    "Shoalar Quanderil",
    "Stegosaurus",
    "Stonemelder",
    "Succubus/Incubus",
    "The Pudding King",
    "Warlock of the Archfey",
    "Wereboar",
    "Weretiger",
    "Yakfolk Priest",
    "Yestabrod",
    "Yeth Hound",
    "Yuan-ti Mind Whisperer",
    "Yuan-ti Nightmare Speaker",
    "Accursed Defiler",
    "Angler Worm",
    "Giant Ant Queen",
    "Bereginyas",
    "Carrion Beetle",
    "Cavelight Moss",
    "Dau",
    "Death Butterfly Swarm",
    "Deep One Hybrid Priest",
    "Derro Fetal Savant",
    "Domovoi",
    "Dorreq",
    "Ash Drake",
    "Edimmu",
    "Shadow Fey Guardian",
    "Firebird",
    "Forest Marauder",
    "Frostveil",
    "Ghoul, Imperial",
    "Flab Giant",
    "Kobold Chieftain",
    "Lemurfolk Greyfur",
    "Lich Hound",
    "Mngwa",
    "Deathcap Myconid",
    "Nkosi Pridelord",
    "Oculo Swarm",
    "Ostinato",
    "Ratatosk",
    "Sap Demon",
    "Selang",
    "Serpopard",
    "Skitterhaunt",
    "Manabane Scarab Swarm",
    "Trollkin Reaver",
    "Tusked Skyfish",
    "Vaettir",
    "Water Leaper",
    "Wharfling Swarm",
    "Zimwi",
    "Bandit Lord",
    "City Watch Captian"
  ],
  [
    "Air Elemental",
    "Banderhobb",
    "Barbed Devil",
    "Barlgura",
    "Beholder Zombie",
    "Brontosaurus",
    "Bulette",
    "Cambion",
    "Captain Othelstan",
    "Catoblepas",
    "Dragonfang",
    "Drow Elite Warrior",
    "Earth Elemental",
    "Elizar Dryflagon",
    "Enchanter",
    "Fire Elemental",
    "Flesh Golem",
    "Giant Crocodile",
    "Giant Shark",
    "Gladiator",
    "Gorgon",
    "Greater Zombie",
    "Half-Red Dragon Veteran",
    "Hellenrae",
    "Hill Giant",
    "Hulking Crab",
    "Izek Strazni",
    "Kraken Priest",
    "Master Thief",
    "Mezzoloth",
    "Mindwitness",
    "Night Hag",
    "Otyugh",
    "Razerblast",
    "Red Slaad",
    "Revenant",
    "Rictavio",
    "Roper",
    "Sahuagin Baron",
    "Salamander",
    "Sea Lion",
    "Shambling Mound",
    "Spawn of Kyuss",
    "Swarm of Cranium Rats",
    "Talis the White",
    "Tanarukk",
    "Tlincalli",
    "Transmuter",
    "Triceratops",
    "Troll",
    "Umber Hulk",
    "Unicorn",
    "Vampire Spawn",
    "Water Elemental",
    "Werebear",
    "Wood Woad",
    "Wraith",
    "Xorn",
    "Young Remorhaz",
    "Yuan-ti Pit Master",
    "Fidele Angel",
    "Aridni",
    "Asanbosam",
    "Bouda",
    "Clockwork Abomination",
    "Spawn Of Akyishigal",
    "Derro Shadow Antipaladin",
    "Spawn Of Arbeyach",
    "Ngobou",
    "Young Spinosaurus",
    "Dogmole Juggernaut",
    "Drakon",
    "Dream Eater",
    "Drowned Maiden",
    "Eleinomae",
    "Shadow Fey Forest Hunter",
    "Fellforged",
    "Ghoul, Iron",
    "Sand Hag",
    "Owl Harpy",
    "Hound Of The Night",
    "Hulking Whelp",
    "Kikimora",
    "Kongamato",
    "Lindwurm",
    "Lorelei",
    "Mi-Go",
    "Corrupting Ooze",
    "Rat King",
    "Ravenala",
    "Ravenfolk Doom Croaker",
    "Rift Swine",
    "Sandman",
    "Sarcophagus Slime",
    "Subek",
    "Temple Dog",
    "Tosculi Elite Bow Raider",
    "Vapor Lynx",
    "Vila",
    "Wormhearted Suffragan",
    "Zmey Headling",
    "Black Knight Commander"
  ], 
  [
    "Wendigo",
    "Annis Hag",
    "Bodak",
    "Centaur Mummy",
    "Chasme",
    "Chimera",
    "Conjurer",
    "Cyclops",
    "Drider",
    "Drider Spellcaster",
    "Flamewrath",
    "Galeb Duhr",
    "Gauth",
    "Githzerai Zerth",
    "Hobgoblin Warlord",
    "Invisible Stalker",
    "Kuo-Toa Archpriest",
    "Mage",
    "Mammoth",
    "Medusa",
    "Miraj Vizann",
    "Mouth of Grolantor",
    "Rath Modar",
    "Vrock",
    "Warlock of the Great Old One",
    "Wyvern",
    "Young Brass Dragon",
    "Young White Dragon",
    "Angatra",
    "Clockwork Myrmidon",
    "Greater Death Butterfly Swarm",
    "Apau Perape",
    "Crystalline Devil",
    "Salt Devil",
    "Young Mithral Dragon",
    "Young Wind Dragon",
    "Shadow Fey Duelist",
    "Fate Eater",
    "Fext",
    "Gbahali (Postosuchus)",
    "Gearforged Templar",
    "Gnarljak",
    "Mirror Hag",
    "Ice Maiden",
    "Likho",
    "Loxoda",
    "Malphas (Storm Crow)",
    "Mamura",
    "Nichny",
    "Nightgarm",
    "Redcap",
    "Adult Rime Worm",
    "Rotting Wind",
    "Rusalka",
    "Sand Silhouette",
    "Sandwyrm",
    "Scheznyki",
    "Spectral Guardian",
    "Wolf Spirit Swarm",
    "Weeping Treant",
    "White Ape",
    "Ghost Knight",
    "Ogre Chieftain, Corrupted"
  ],
  [
    "Aerisi Kalinoth",
    "Air Elemental Myrmidon",
    "Bheur Hag",
    "Blue Slaad",
    "Draegloth",
    "Dragonsoul",
    "Drannin Splithelm",
    "Drow Mage",
    "Earth Elemental Myrmidon",
    "Fire Elemental Myrmidon",
    "Ghald",
    "Giant Ape",
    "Grick Alpha",
    "Korred",
    "Mind Flayer",
    "Oni",
    "Rezmir",
    "Shield Guardian",
    "Stone Giant",
    "Tree Blight",
    "Warlock of the Fiend",
    "Water Elemental Myrmidon",
    "Young Black Dragon",
    "Young Copper Dragon",
    "Yuan-ti Abomination",
    "Chelicerae",
    "Deathwisp",
    "Psoglav Demon",
    "Gilded Devil",
    "Dissimortuum",
    "Coral Drake",
    "Elder Shadow Drake",
    "Einherjar",
    "Shadow Fey Enchantress",
    "Red Hag",
    "Herald Of Darkness",
    "Possessed Pillar",
    "Risen Reaver",
    "Shadow Beast",
    "Soul Eater",
    "Spark",
    "Sand Spider",
    "Spider Of Leng",
    "Fire Dancer Swarm",
    "Lake Troll",
    "Umbral Vampire",
    "Vine Lord",
    "Dwarven Ringmage"
  ],
  [
    "Assassin",
    "Bastian Thermandar",
    "Blackguard",
    "Cloaker",
    "Diviner",
    "Drow Priestess of Lolth",
    "Ezmerelda d'Avenir",
    "Fomorian",
    "Frost Giant",
    "Githyanki Knight",
    "Green Slaad",
    "Hezrou",
    "Hydra",
    "Marlos Urnrayle",
    "Mind Flayer Arcanist",
    "Mind Flayer Psion",
    "Shoosuva",
    "Spirit Naga",
    "Tyrannosaurus Rex",
    "Young Bronze Dragon",
    "Young Green Dragon",
    "Ala",
    "Angel, Chained",
    "Blemmyes",
    "Bone Collective",
    "Chronalmental",
    "Deep One Archimandrite",
    "Kishi Demon",
    "Lunar Devil",
    "Young Cave Dragon",
    "Dragonleaf Tree",
    "Rust Drake",
    "Dune Mimic",
    "Feyward Tree",
    "Idolic Deity",
    "Liosalfar",
    "Mallqui",
    "Monolith Champion",
    "Qwyllion",
    "Savager",
    "Shabti",
    "Degenerate Titan",
    "Tophet",
    "Xhkarsh",
    "Emerald Order Cult Leader"
  ],
  [
    "Abjurer",
    "Abominable Yeti",
    "Blagothkus",
    "Champion",
    "Clay Golem",
    "Cloud Giant",
    "Evoker",
    "Fire Giant",
    "Flind",
    "Gar Shatterkeel",
    "Glabrezu",
    "Gray Slaad",
    "Necromancer",
    "Neronvain",
    "Nycaloth",
    "Treant",
    "Ulitharid",
    "Vanifer",
    "War Priest",
    "Young Blue Dragon",
    "Young Silver Dragon",
    "Bukavac",
    "Malakbel",
    "Young Flame Dragon",
    "Young Sea Dragon",
    "Young Void Dragon",
    "Deep Drake",
    "Eater Of Dust (Yakat-Shi)",
    "Al-Aeshma Genie",
    "Desert Giant",
    "Horakh",
    "Krake Spawn",
    "Oozasis",
    "Vine Troll Skeleton",
    "Ghostwalk Spider",
    "Ushabti",
    "Devilbound Gnomish Prince"
  ],
  [
    "Aboleth",
    "Alhoon",
    "Death Kiss",
    "Death Slaad",
    "Deva",
    "Froghemoth",
    "Guardian Naga",
    "Madam Eva",
    "Malformed Kraken",
    "Ooze Master",
    "Rahadin",
    "Stone Giant Dreamwalker",
    "Stone Golem",
    "White Maw",
    "Yochlol",
    "Young Gold Dragon",
    "Young Red Dragon",
    "Algorith",
    "Bone Swarm",
    "Rubezahl",
    "Automata Devil",
    "Fear Smith",
    "Salt Golem",
    "Hundun",
    "Sathaq Worm",
    "Thuellai"
  ],
  [
    "Baba Lysaga",
    "Baba Lysaga's Creeping Hut",
    "Behir",
    "Chain Devil",
    "Cloud Giant Smiling One",
    "Dao",
    "Djinni",
    "Efreeti",
    "Gynosphinx",
    "Horned Devil",
    "Marid",
    "Morkoth",
    "Naergoth Bladelord",
    "Remorhaz",
    "Roc",
    "Severin",
    "Abominable Beauty",
    "Baba Yaga's Horsemen, Black Night",
    "Baba Yaga's Horsemen, Bright Day",
    "Baba Yaga's Horsemen, Red Sun",
    "Buraq",
    "Corpse Mound",
    "Berstuc",
    "Koralk (Harvester Devil)",
    "Dullahan",
    "Eye Golem",
    "Grim Jester",
    "Blood Hag",
    "Naina",
    "Valkyrie",
    "Vesiculosa",
    "Voidling",
    "Ychen Bannog"
  ],
  [
    "Arcanaloth",
    "Archdruid",
    "Archmage",
    "Bone Devil",
    "Bone Devil Polearm",
    "Erinyes",
    "Frost Giant Everlasting One",
    "Ki-rin",
    "Warlord",
    "Yuan-ti Anathema",
    "Akyishigal, Demon Lord Of Cockroaches",
    "Chort Devil",
    "Dragon Eel",
    "Bear King",
    "Flutterflesh",
    "Bonepowder Ghoul",
    "Hoard Golem",
    "Gug",
    "Herald Of Blood",
    "Mavka",
    "Skein Witch",
    "Son Of Fenris",
    "Ancient Titan",
    "Titanoboa",
    "Tosculi Hive-Queen"
  ],
  [
    "Adult Brass Dragon",
    "Adult White Dragon",
    "Beholder",
    "Devourer",
    "Nalfeshnee",
    "Neothelid",
    "Rakshasa",
    "Storm Giant",
    "Tarul Var",
    "Ultroloth",
    "Vampire",
    "Young Red Shadow Dragon",
    "Spinosaurus",
    "Steam Golem",
    "Haugbui",
    "Mask Wight",
    "Stuhac",
    "Vampire Warlock - Variant"
  ],
  [
    "Adult Black Dragon",
    "Adult Copper Dragon",
    "Death Tyrant",
    "Elder Brain",
    "Fire Giant Dreadnought",
    "Ice Devil",
    "Ice Devil Spear",
    "Cambium",
    "Orobas Devil",
    "Adult Mithral Dragon",
    "Adult Void Dragon",
    "Smaragdine Golem",
    "Isonade",
    "Gypsosphinx",
    "Zmey"
  ],
  [
    "Adult Bronze Dragon",
    "Adult Green Dragon",
    "Mummy Lord",
    "Purple Worm",
    "Vampire Spellcaster",
    "Vampire Warrior",
    "Andrenjinyi",
    "Ia'affrat",
    "Star Drake",
    "Mordant Snare",
    "Slow Storm",
    "Star Spawn Of Cthulhu"
  ],
  [
    "Adult Blue Dragon",
    "Adult Silver Dragon",
    "Iron Golem",
    "Marilith",
    "Planetar",
    "Storm Giant Quintessent",
    "Adult Cave Dragon",
    "Adult Flame Dragon",
    "Adult Sea Dragon",
    "River King",
    "Snow Queen"
  ],
  [
    "Adult Blue Dracolich",
    "Adult Gold Dragon",
    "Adult Red Dragon",
    "Androsphinx",
    "Death Knight",
    "Dragon Turtle",
    "Goristro",
    "Avatar Of Boreas",
    "Adult Wind Dragon",
    "Elemental Locus",
    "Moonlit King",
    "Queen Of Witches",
    "Koschei",
    "Urochar (Strangling Watcher)"
  ],
  [
    "Demilich",
    "Olhydra",
    "Yan-C-Bin",
    "Ancient Mithral Dragon",
    "Lord Of The Hunt"
  ],
  [
    "Balor",
    "Imix",
    "Hraesvelgr The Corpse Swallower",
    "Shoggoth"
  ],
  [
    "Ancient Brass Dragon",
    "Ancient White Dragon",
    "Ogremoch",
    "Pit Fiend",
    "Emperor Of The Ghouls"
  ],
  [
    "Ancient Black Dragon",
    "Ancient Copper Dragon",
    "Lich",
    "Solar",
    "Alquam, Demon Lord Of Night",
    "Arbeyach",
    "Queen Of Night And Magic"
  ],
  [
    "Ancient Bronze Dragon",
    "Ancient Green Dragon",
    "Illithilich",
    "Camazotz, Demon Lord Of Bats And Fire",
    "Ancient Sea Dragon",
    "Ancient Wind Dragon",
    "Jotun Giant"
  ],
  ["Big Bad Boss, Biggest and Baddest of Monsters","Big Bad Boss, Biggest and Baddest of Monsters","Big Bad Boss, Biggest and Baddest of Monsters"]
];